In [31]:
# -*- coding: utf-8 -*-
import torch
import numpy as np
from torch.autograd import Variable
import torch.nn.functional as F


pytorch 自动求导说明 需要补充

out = $  \frac{1}{4} \sum_{i}(Z_j) $
$$ Z_j =  (W*X + 2)^2 *3 $$  $$ \frac{d_z}{d_w} = $$   

In [46]:
x = Variable(torch.ones(2,2),requires_grad=True)
w = Variable(torch.randint(1, 2, (2,)),requires_grad=True)

y = w*x + 2
# print(x.creator)      # None,用户直接创建没有creater属性
print(y.grad_fn)      # <torch.autograd._functions.basic_ops.AddConstant object at 0x7fb9b4d4b208>
z = y * y * 3
out = z.mean()
print(out)
out.backward()
# 梯度更新
print(x.grad.data)
d_p = x.grad.data
x.data.add_(-0.1,d_p) # 1 + (-0.1) * 4.5 = 0.55  根据导数及学习率，更新数据
print(x.data)


tensor(27.)
tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])
tensor([[ 0.5500,  0.5500],
        [ 0.5500,  0.5500]])


pytorch 损失函数学习
1、cross_entropy : This criterion combines log_softmax and nll_loss in a single function. 可用于分类问题, torch.nn.CrossEntropyLoss，需
   再仔细看一下其推导过程
2、nll_loss :  The negative log likelihood loss. 负对数似然损失函数, 主要用于分类问题 https://www.bilibili.com/video/av15474329/


In [37]:
# cross entropy example
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
loss = F.cross_entropy(input, target)
loss.backward()
print(input,target)
print("*"*20)
print(input.grad.data)


tensor([[ 1.0405,  0.2065, -0.1137,  0.3112, -1.5401],
        [-0.8510, -0.2648, -0.7867,  0.4211,  1.3341],
        [ 1.4545,  0.8318,  0.2347,  1.6478,  0.9291]]) tensor([ 1,  0,  0])
********************
tensor([[ 0.1445, -0.2706,  0.0455,  0.0697,  0.0109],
        [-0.3129,  0.0367,  0.0218,  0.0729,  0.1816],
        [-0.2417,  0.0492,  0.0271,  0.1112,  0.0542]])
Object `torch.nn.nll_loss` not found.


torch.optim是一个实现了各种优化算法的库。大部分常用的方法得到支持，并且接口具备足够的通用性，使得未来能够集成更加复杂的方法。
Note: You can still pass options as keyword arguments. They will be used as defaults, in the groups that didn’t override them. This is useful when you only want to vary a single option, while keeping all others consistent between parameter groups.
For example, this is very useful when one wants to specify per-layer learning rates:

optim.SGD([
                {'params': model.base.parameters()},
                {'params': model.classifier.parameters(), 'lr': 1e-3}
            ], lr=1e-2, momentum=0.9)

This means that model.base’s parameters will use the default learning rate of 1e-2, model.classifier’s parameters will use a learning rate of 1e-3, and a momentum of 0.9 will be used for all parameters



1、torch.optim.SGD 实现随机梯度下降算法, 参数 momentum 表势能  weight decay (L2 penalty)  https://byjiang.com/2017/09/10/A_Brief_Of_Optimization_Algorithms/ ； https://www.cnblogs.com/qniguoym/p/8058186.html. 

https://discuss.pytorch.org/t/how-does-pytorch-handle-the-mini-batch-training/9707/5  How does pytorch handle the mini-batch training?

In [ ]:
# torch.optim.SGD  实现随机梯度下降算法