# 基本说明

Use TensorBoard with tensorboard --logdir runs (needs to install TensorFlow)
用于跟踪训练数据
在命令行运行  tensorboard.exe --logdir="d:\\tmp"
1、记录学习速度(learning rate)的如何变化，以及目标函数如何变化。通过向节点附加scalar_summary操作来分别输出学习速度和期望误差。你可以给每个 scalary_summary 分配一个有意义的 标签，比如 'learning rate' 和 'loss function'。
2、显示一个特殊层中激活的分布，或者梯度权重的分布。可以通过分别附加 histogram_summary 运算来收集权重变量和梯度输出。

需要再进一步通过简单实例了解其各项图形的具体含义，及怎么应用。

In [6]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import torch
import torchvision.utils as vutils
import numpy as np
import torchvision.models as models
from torchvision import datasets
from tensorboardX import SummaryWriter

resnet18 = models.resnet18(False)
writer = SummaryWriter("/home/hecong/dplearn/base/log")
sample_rate = 44100
freqs = [262, 294, 330, 349, 392, 440, 440, 440, 440, 440, 440]


for n_iter in range(100):

    dummy_s1 = torch.rand(1)
    dummy_s2 = torch.rand(1)
    # data grouping by `slash`
    writer.add_scalar('data/scalar1', dummy_s1[0], n_iter)
    writer.add_scalar('data/scalar2', dummy_s2[0], n_iter)

    writer.add_scalars('data/scalar_group', {'xsinx': n_iter * np.sin(n_iter),
                                             'xcosx': n_iter * np.cos(n_iter),
                                             'arctanx': np.arctan(n_iter)}, n_iter)

    dummy_img = torch.rand(32, 3, 64, 64)  # output from network
    if n_iter % 10 == 0:
        x = vutils.make_grid(dummy_img, normalize=True, scale_each=True)
        writer.add_image('Image', x, n_iter)

        dummy_audio = torch.zeros(sample_rate * 2)
        for i in range(x.size(0)):
            # amplitude of sound should in [-1, 1]
            dummy_audio[i] = np.cos(freqs[n_iter // 10] * np.pi * float(i) / float(sample_rate))
        writer.add_audio('myAudio', dummy_audio, n_iter, sample_rate=sample_rate)

        writer.add_text('Text', 'text logged at step:' + str(n_iter), n_iter)

        for name, param in resnet18.named_parameters():
            writer.add_histogram(name, param.clone().cpu().data.numpy(), n_iter)

        # needs tensorboard 0.4RC or later
        writer.add_pr_curve('xoxo', np.random.randint(2, size=100), np.random.rand(100), n_iter)

dataset = datasets.MNIST('mnist', train=False, download=True)
images = dataset.test_data[:100].float()
label = dataset.test_labels[:100]

features = images.view(100, 784)
writer.add_embedding(features, metadata=label, label_img=images.unsqueeze(1))

# export scalar data to JSON for external processing
writer.export_scalars_to_json("/home/hecong/dplearn/base/log/all_scalars.json")
writer.close()

Processing...
Done!


In [13]:
for name, param in resnet18.named_parameters():
    print(name)
    print(param)

conv1.weight
Parameter containing:
tensor([[[[-9.2618e-03,  1.2332e-02,  5.3802e-03,  ...,  2.0851e-02,
           -2.5315e-02,  4.4135e-02],
          [-1.4653e-02, -1.6115e-02, -3.3083e-02,  ..., -2.8530e-02,
            8.1732e-03,  2.3628e-02],
          [-2.4232e-02, -8.5120e-03,  2.6125e-02,  ..., -9.2657e-03,
            3.2968e-03, -3.3235e-02],
          ...,
          [ 4.1989e-02, -1.8395e-03,  2.8938e-02,  ..., -2.3970e-02,
            3.6821e-02,  2.9323e-02],
          [ 6.3159e-02, -1.9951e-02, -2.9526e-02,  ..., -2.5977e-02,
           -2.4296e-02,  1.8652e-03],
          [-1.5345e-02,  3.3768e-02,  6.5706e-03,  ...,  6.8285e-03,
            1.8076e-02, -1.1542e-03]],

         [[-1.6179e-02,  2.3984e-02,  1.0285e-02,  ...,  4.0442e-02,
           -1.8541e-03,  3.1598e-02],
          [-5.0731e-02, -2.2965e-03, -1.7148e-02,  ...,  2.3002e-02,
           -9.5387e-03, -3.7558e-03],
          [ 2.0501e-02,  4.5131e-02,  9.4568e-03,  ...,  1.8515e-02,
           -9.0360e-03,

            8.9147e-03, -4.9202e-03]]]])
bn1.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.])
bn1.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.])
layer1.0.conv1.weight
Parameter containing:
tensor([[[[ 6.1062e-02, -5.3022e-02, -3.5266e-02],
          [-2.5555e-04, -5.3591e-03, -2.9863e-02],
          [

          [ 6.7067e-02,  4.0991e-02,  4.2665e-02]]]])
layer1.0.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.])
layer1.0.bn2.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.])
layer1.1.conv1.weight
Parameter containing:
tensor([[[[-3.6084e-02, -5.2643e-02,  2.6288e-02],
          [ 1.9623e-02, -2.9148

          [-1.5086e-02,  2.2817e-02,  2.1873e-02]]]])
layer1.1.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.])
layer1.1.bn2.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.])
layer2.0.conv1.weight
Parameter containing:
tensor([[[[-2.2416e-02,  2.2460e-02, -5.5198e-02],
          [ 2.3958e-02, -5.3000

          [-3.1645e-02, -3.0378e-03,  6.4885e-02]]]])
layer2.0.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
layer2.0.bn2.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,

          [-5.6508e-02,  1.3610e-02, -7.4997e-03]]]])
layer2.1.bn1.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
layer2.1.bn1.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,

         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
layer3.0.conv1.weight
Parameter containing:
tensor([[[[-2.3883e-02,  3.0059e-02, -1.2339e-02],
          [ 2.1645e-02, -6.9129e-03,  2.9048e-04],
          [ 2.3085e-02,  1.8854e-02,  2.6042e-02]],

         [[-1.4822e-02, -1.3877e-02,  3.7964e-03],
          [ 4.4727e-02,  2.0939e-02, -5.5047e-02],
          [-1.9716e-02,  9.2956e-03, -2.0433e-02]],

         [[-3.5262e-02,  4.3387e-02, -1.4626e-02],
          [ 2.0718e-03, -6.7394e-02, -1.0549e-02],
          [ 1.0021e-02,  2.6657e-02, -4.8303e-02]],

         ...,

         [[ 1.3430e-02,  8.3367e-03,  8.0747e-03],
          [ 1.2422e-02, -1.4247e-02,  2.6303e-02],
          [ 5.1166e-02,  8.5083e-03,  4.1496e-02]],

         [[ 3.8918e-05, -5.4181e-02, -4.1380e-02],
          [-1.5460e-02,  3.6121e-02, -5.0840e-02],
          [ 3.4957e-02,  2.1917e-02,  2.2482e-02]],

         [[ 6.8579e-03, -1.0149e-02, -1.4037e-02],
          [ 4.6985e-03,  2.0259e-02, -2.6187e-03],
          [-2.2

         0.,  0.,  0.,  0.])
layer3.0.conv2.weight
Parameter containing:
tensor([[[[ 1.9085e-02,  3.1175e-03,  5.0493e-03],
          [-1.0405e-02,  3.4635e-04,  8.0027e-04],
          [ 3.0584e-02,  7.0285e-02, -5.0690e-02]],

         [[-2.6629e-02,  9.9961e-04, -2.8040e-02],
          [-2.3285e-02,  1.6127e-02,  3.9846e-02],
          [ 1.3426e-02, -4.9201e-02,  1.4716e-02]],

         [[ 1.9001e-02, -2.7344e-02, -3.0519e-02],
          [-3.2859e-02, -3.7759e-02,  3.8073e-02],
          [ 5.0738e-02,  3.7985e-02,  3.0118e-03]],

         ...,

         [[-3.6422e-02, -2.8649e-02, -8.7187e-03],
          [-1.4698e-03, -2.7389e-02, -3.1159e-03],
          [ 3.1757e-02,  8.7704e-03,  2.5962e-02]],

         [[-3.7330e-02,  1.0273e-02,  4.8790e-02],
          [ 7.6734e-03,  6.1525e-03,  3.5132e-02],
          [ 3.3063e-02,  4.7819e-02,  5.2489e-02]],

         [[ 5.2526e-02, -9.3052e-03,  8.2059e-03],
          [ 7.9258e-02, -3.0271e-02, -1.7807e-02],
          [-2.7769e-02, -8.0339e-03

         0.,  0.,  0.,  0.])
layer3.0.downsample.0.weight
Parameter containing:
tensor([[[[-3.1861e-03]],

         [[-1.5282e-01]],

         [[ 9.9098e-02]],

         ...,

         [[ 3.3130e-02]],

         [[-5.0838e-02]],

         [[-5.9240e-02]]],


        [[[ 5.4943e-02]],

         [[ 2.0577e-02]],

         [[ 1.3711e-01]],

         ...,

         [[-1.4220e-01]],

         [[ 1.1625e-01]],

         [[-1.0549e-01]]],


        [[[-1.7272e-01]],

         [[-5.7579e-02]],

         [[-2.4245e-02]],

         ...,

         [[-5.6364e-03]],

         [[-5.3714e-02]],

         [[-1.1204e-02]]],


        ...,


        [[[ 6.6226e-02]],

         [[ 8.0518e-03]],

         [[-2.2841e-02]],

         ...,

         [[ 2.2795e-02]],

         [[-2.0777e-02]],

         [[-7.6885e-02]]],


        [[[-5.4393e-02]],

         [[ 1.3690e-02]],

         [[-5.7081e-02]],

         ...,

         [[ 1.6905e-02]],

         [[ 7.8679e-02]],

         [[ 9.4465e-02]]],


        [[

          [-5.9014e-03,  5.9246e-02, -4.6919e-02]]]])
layer3.1.bn1.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

          [-4.2802e-02, -1.7427e-02, -1.0748e-02]]]])
layer3.1.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

          [-1.2907e-02, -1.1574e-02, -4.3029e-02]]]])
layer4.0.bn1.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

          [-1.8813e-02, -3.3271e-02, -1.2642e-02]]]])
layer4.0.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
layer4.0.downsample.1.bias
Parameter containing:
tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., 

          [ 7.5098e-03,  1.4950e-02, -2.6232e-02]]]])
layer4.1.bn1.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

          [-5.3111e-03,  1.5786e-02, -2.8468e-02]]]])
layer4.1.bn2.weight
Parameter containing:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1

         1.4120,  1.6118, -1.8203,  3.8000,  2.0716,  1.0068])


# 怎么样观察梯度情况

    https://stackoverflow.com/questions/48816873/intermediate-layer-makes-tensorflow-optimizer-to-stop-working
    
    
    https://tensorboard-pytorch.readthedocs.io/en/latest/tensorboard.html
    
    
    https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/04-utils/tensorboard   pytorch - tensorboard
    
    https://github.com/L1aoXingyu/pytorch-beginner/tree/master/04-Convolutional%20Neural%20Network
    
    tensorboard summaries for the variables and gradients
    
    The charts show the distributions of W:0 variable (the first layer) and how they are changed from 0 epoch to 1000 (clickable). Indeed, we can see, the rate of change is much higher in a 2-layer network. But I'd like to pay attention to the gradient distribution, which is much closer to 0 in a 3-layer network (first variance is around 0.005, the second one is around 0.000002, i.e. 1000 times smaller). This is the vanishing gradient problem.
    
    
    Here's the helper code if you're interested:

    for g, v in grads_and_vars:
      tf.summary.histogram(v.name, v)
      tf.summary.histogram(v.name + '_grad', g)

    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter('train_log_layer2', tf.get_default_graph())

    ...

    _, summary = sess.run([train_op, merged], feed_dict={I: 2*np.random.rand(1, 1)-1})
    if i % 10 == 0:
      writer.add_summary(summary, global_step=i)
      
      