In [1]:
# Put these at the top of every notebook, to get automatic reloading and inline plotting
%reload_ext autoreload
%autoreload 2
%matplotlib inline
import numpy as np

1、
ptp()函数返回沿轴的值的范围(最大值 - 最小值)。

In [4]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print(np.ptp(a))
print(np.ptp(a, axis =  1))
print(np.ptp(a, axis =  0))

7
[4 5 7]
[6 3 6]


2、
percentile() 百分位数是统计中使用的度量，表示小于这个值得观察值占某个百分比。  ？？？

In [7]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])  
print(np.percentile(a,50))  
print(np.percentile(a,50, axis =  1) )  0.5

50.0
[40. 20. 60.]


3、
median() 中值定义为将数据样本的上半部分与下半部分分开的值。

In [6]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])  
print(np.median(a,axis=1))

4、
average() 加权平均值是由每个分量乘以反映其重要性的因子得到的平均值。 average()函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。 考虑数组[1,2,3,4]和相应的权重[4,3,2,1]，通过将相应元素的乘积相加，并将和除以权重的和，来计算加权平均值。
加权平均值 = (1*4+2*3+3*2+4*1)/(4+3+2+1)

5、
标准差，标准差是与均值的偏差的平方的平均值的平方根。std = sqrt(mean((x - x.mean())**2))
print np.std([1,2,3,4])
1.1180339887498949

6、
方差 方差是偏差的平方的平均值，即mean((x - x.mean())** 2)。 换句话说，标准差是方差的平方根。
print np.var([1,2,3,4])
1.25

7、
梯度，连续值之间的变化率，即斜率XY坐标轴连续三个X坐标对应的Y轴值：a, b, c，其中，b的梯度是： (c‐a)/2   ? ? ?

In [14]:
a = np.random.randint(0, 20, (5))
print(a)
print(np.gradient(a))
print("*" * 20)
c = np.random.randint(0, 20, (3, 5))
print(c)
print(np.gradient(c))

[ 2 15  3 13  6]
[13.   0.5 -1.   1.5 -7. ]
********************
[[ 4  5  0 17  9]
 [ 0  5 13  6  6]
 [ 1  1  5  4 18]]
[array([[ -4. ,   0. ,  13. , -11. ,  -3. ],
       [ -1.5,  -2. ,   2.5,  -6.5,   4.5],
       [  1. ,  -4. ,  -8. ,  -2. ,  12. ]]), array([[ 1. , -2. ,  6. ,  4.5, -8. ],
       [ 5. ,  6.5,  0.5, -3.5,  0. ],
       [ 0. ,  2. ,  1.5,  6.5, 14. ]])]


8、
相关程度 有两组数据时，我们关心这两组数据是否相关，相关程度有多少。用协方差（COV）和相关系数（CORRCOEF）来衡量相关程度：
![Image of Yaktocat](https://images2015.cnblogs.com/blog/927391/201604/927391-20160428164241783-360115652.png)
协方差的绝对值越大表示相关程度越大，协方差为正值表示正相关，负值为负相关，0为不相关。相关系数是基于协方差但进行了无量纲处理。使用NumPy计算协方差和相关系数：
 1 from numpy import array, cov, corrcoef
 2 
 3 data = array([data1, data2])
 4 
 5 #计算两组数的协方差
 6 #参数bias=1表示结果需要除以N，否则只计算了分子部分
 7 #返回结果为矩阵，第i行第j列的数据表示第i组数与第j组数的协方差。对角线为方差
 8 cov(data, bias=1)
 9 
10 #计算两组数的相关系数
11 #返回结果为矩阵，第i行第j列的数据表示第i组数与第j组数的相关系数。对角线为1
12 corrcoef(data)

9、 汇总统计

In [17]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from pandas import DataFrame as df
 
column=load_iris().feature_names
data=load_iris().data
target=load_iris().target
df1=df(data,columns=column)
df2=df(target,columns=['target'])
data_df=pd.concat([df1,df2],axis=1)

print(data_df.shape)
print(data_df[1:10])
print(data_df.describe())

(150, 5)
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         1